### ISSUE TITLE
[Bug] Test fail on duplicate found

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_apple_store#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Test fail due to records not unique on `date_day`, `app_platform`, `app_name`, and `country_short`. My data is displaying duplicate records for country code `TR`:

<img width="1024" alt="image" src="https://github.com/fivetran/dbt_apple_store/assets/6558178/4146ce8f-ba16-4fca-a280-8475c2f2ecdf">

### Relevant error log or model output

```
Failure in test dbt_utils_unique_combination_of_columns_app_reporting__country_report_date_day__app_platform__app_name__country_short (models/app_reporting.yml)
```

### Expected behavior

No errors

### dbt Project configurations

N/A

### Package versions

0.3.0

### What database are you using dbt with?

snowflake

### dbt Version

1.5

### Additional Context

See [this issue](https://github.com/fivetran/dbt_google_play/issues/8) on Google Play for additional background.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @raphaelvarieras thanks for opening this issue! I think this can actually be an easy fix since the country_code_long is unique. We may just need to adjust the test to incorporate the country_code_long as well.

Would you be concerned with the data if we adjusted that test?

**Comment by raphaelvarieras** [comment]
No, no particularly concerned. I am much more concerned that Google and now Apple don't seem to vet any of the data they're publishing on their app stores!

**Comment by fivetran-joemarkiewicz** [comment]
I would agree with you there! Thanks @raphaelvarieras, I will plan to have someone from my team work on these test updates in the coming sprint. Thanks again!

**Comment by fivetran-joemarkiewicz** [comment]
@raphaelvarieras I actually had some free time this morning and was able to get around to working on the bugfix. If you have time, would you be able to test the WIP branch I have with the test modification applied. Let me know if this resolves the test error on your end!

```yml
packages:
  - git: https://github.com/fivetran/dbt_app_reporting.git
    revision: bugfix/country-long-test-addition
    warn-unpinned: false 
```

Let me know if you have any questions!
