### ISSUE TITLE
[Bug] cannot download latest version (0.2.0) via dbt Hub

### ISSUE THREAD

**Issue by lch88** [fivetran/dbt_apple_store#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I tried installing the latest version of package (0.2.0) by following the guide in the README.md.

But it failed with following error,
```
08:34:10  Running with dbt=1.3.1
08:34:12  Encountered an error:
Could not find a matching compatible version for package fivetran/apple_store
  Requested range: >=0.2.0, <0.3.0
  Compatible versions: ['0.1.0']
```

It was weired at first since I just followed the instruction. It turns out that the package info on the dbt Hub hasn't been updated yet.

A little more digging revealed that dbt hub seems to auto-update packages by observing changes of their (each package's) GitHub releases.

I think publishing new release will solve the issue.

### Relevant error log or model output

```shell
08:34:10  Running with dbt=1.3.1
08:34:12  Encountered an error:
Could not find a matching compatible version for package fivetran/apple_store
  Requested range: >=0.2.0, <0.3.0
  Compatible versions: ['0.1.0']
```

### Expected behavior

One should be able to download latest version of apple_store package from dbt Hub.

### dbt Project configurations

not changed from auto-generated default 

### Package versions

packages:
  - package: fivetran/apple_store
    version: [">=0.2.0", "<0.3.0"]

### What database are you using dbt with?

snowflake

### dbt Version

Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - snowflake: 1.3.0 - Up to date!

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @lch88 thanks for opening this issue.

While we have merged the latest version of the package to the GitHub repo, it is not yet live on the dbt hub. We were planning to release this update during this week! You should see this issue resolved in the next day or so.

For more updates around this migration, you can look to our [tools-fivetran channel](https://getdbt.slack.com/archives/C01D1R2JLLA/p1671052979225199) within dbt slack for more info!

**Comment by lch88** [comment]
Thanks, @fivetran-joemarkiewicz!
Got it, I'll check it out again in a day or two.

**Comment by lch88** [comment]
I tried again and downloaded new pacakge version. Thanks!
