### ISSUE TITLE
[Bug] ERD readme link is a 404

### ISSUE THREAD

**Issue by chrisweis** [fivetran/dbt_apple_store#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Clicking the link "ERD" in the home page of this repo fails with a 404 error.

### Relevant error log or model output

```shell
URL: https://fivetran.com/docs/applications/apple_store/#schemainformation
```

### Expected behavior

No 404

### dbt Project configurations

N/A (markdown only)

### Package versions

Latest

### What database are you using dbt with?

other (mention it in "Additional Context")

### dbt Version

N/A

### Additional Context

N/A

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @chrisweis thanks so much for opening this issue. It looks like we miss typed the full app name for the ERD hyperlink.

After taking a look, it looks like it should in fact be: https://fivetran.com/docs/applications/apple-app-store#salesandfinancereportschema.

I noticed you are open to creating a PR! If you would like, I would be happy to review if you include the link above in place of the link we are currently using. If not, we can address this change as well. Let me know!

**Comment by fivetran-joemarkiewicz** [comment]
@chrisweis thanks again for raising this to our attention. I just updated the link within the README. This should now be addressed. As such, I will close out this issue.
